# Generated by Django 4.2.18 on 2025-04-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emp_department', models.CharField(max_length=100)),
            ],
        ),
    ]
